FROM python:3

WORKDIR /code
EXPOSE 5001

COPY requirements.txt .
RUN apt-get -y update
RUN apt-get -y install build-essential cmake
RUN apt-get -y install libopenblas-dev liblapack-dev 
RUN apt-get -y install libx11-dev libgtk-3-dev
RUN pip install -r requirements.txt

RUN pip3 install --upgrade awscli
COPY ./aws/ /root/.aws/

COPY ./python-server/ .
RUN ["python", "serverless.py"]
CMD ["gunicorn","-b", "0.0.0.0:5001","-w", "2", "server:app", "--timeout", "120"]
